# Generated by Django 6.1.1 on 2026-09-10 14:35

import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatar_upload_path, validators=[users.validators.validate_avatar]),
        ),
    ]
